apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gatepilot-system

resources:
  - gatepilot.yaml

images:
  - name: gatepilot-app
    newName: registry.example.com/gatepilot/gatepilot-app
    newTag: 1.0.0-SNAPSHOT
