<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.dt</groupId>
        <artifactId>getboot-spring-boot-starter-parent</artifactId>
        <version>1.0.0</version>
        <relativePath/>
    </parent>

    <groupId>com.dt.gateway</groupId>
    <artifactId>platform-gateway-parent</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <name>platform-gateway-parent</name>
    <description>独立发布的平台网关工程</description>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <profileActive>local</profileActive>
    </properties>

    <modules>
        <module>platform-gateway-runtime</module>
        <module>platform-gateway-server</module>
    </modules>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.dt.gateway</groupId>
                <artifactId>platform-gateway-runtime</artifactId>
                <version>${project.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>
</project>
