spring:
  profiles:
    active: @profileActive@
  application:
    name: platform-gateway-admin
  cloud:
    gateway:
      enabled: false

server:
  port: 18083

management:
  endpoints:
    web:
      exposure:
        include: health,info,platformGatewayRoutes
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

platform:
  gateway:
    api-prefix: /api
    internal-prefix: /internal
    auth:
      enabled: true
    cors:
      enabled: true
      allowed-origin-patterns:
        - http://127.0.0.1:*
        - http://localhost:*
      allowed-methods:
        - GET
        - POST
        - PUT
        - PATCH
        - DELETE
        - OPTIONS
      allowed-headers:
        - "*"
      exposed-headers:
        - X-Trace-Id
        - X-Traffic-Color
        - Authorization
      allow-credentials: true
      max-age: 1h
    context-headers:
      enabled: true
      project-header-name: X-Platform-Project
      route-header-name: X-Platform-Route
    traffic-color:
      enabled: false
      header-name: X-Traffic-Color
      response-header-enabled: true
      trust-request-header: false
      default-color: stable
    audit:
      enabled: true
      log-enabled: true
      recent-capacity: 5000
      trace-header-name: X-Trace-Id
    projects:
      game:
        enabled: true
        path-segment: game
        display-name: Game Platform
        routes:
          admin:
            enabled: true
            api-enabled: true
            actuator-enabled: true
            path-segment: admin
            service-uri: http://127.0.0.1:18080
            service-path-prefix: /admin
            actuator-uri: http://127.0.0.1:18080
            connect-timeout-ms: 2000
            response-timeout: 5s
            auth:
              required: true
              public-paths:
                - /system/ping
                - /auth/**
          open:
            enabled: true
            api-enabled: true
            actuator-enabled: true
            path-segment: open
            service-uri: http://127.0.0.1:18080
            service-path-prefix: /open
            actuator-uri: http://127.0.0.1:18080
            connect-timeout-ms: 2000
            response-timeout: 5s
            auth:
              required: false
